### ISSUE TITLE
Cannot change mods for present configuration

### ISSUE THREAD

**Issue by Alvo** [Poweruser/OFPMonitor#1]
- you have configured a launch configuration
- after you added the launch configuration you cannot change the list of mody anymore

**Comment by Poweruser** [comment]
Yes, up to v1.26 you can not edit launch configurations. You have to delete it and create a new one. In the next version (1.27 presumably) you can edit them.
This feature has been on the todo-list, and is implemented already.

**Comment by Alvo** [comment]
Yeah it works with ofpmonitor 1.27
