### ISSUE TITLE
Cannot see mission time

### ISSUE THREAD

**Issue by Alvo** [Poweruser/OFPMonitor#3]
In server list panel i cannot see the elapsed time a mission was played. i have to launch ofp to see the mission time. Can this be added?

Chers
Al

**Comment by Poweruser** [comment]
No, the gamespy protocoll doesnt offer any information about the elapsed game time. You can only see the time for those games that were started when ofpmonitor was already running (see in the changelog for v1.25)

Edit: There might be a way (I don't know about yet), by directly talking to the ofp server on port 2302 (status polls are done on port 2303). But that will probably cause more problems than it solves, e.g. server hanging/crashing/lag for those in game.

**Comment by Alvo** [comment]
Yes that enough.
