### ISSUE TITLE
Mission notify

### ISSUE THREAD

**Issue by Alvo** [Poweruser/OFPMonitor#4]
Can there be a mission notification?
It couls work like this:
- enter mission search needle (e.g. "cti" for plain needles or "cti.*res-z" for regular expressions)
- ofpmonitor gives a notification when a mission is created ('Waiting') where the searchexpression hits

**Comment by Poweruser** [comment]
Should be covered with the custom notifications added in v1.31

**Comment by Alvo** [comment]
works good!
2 issues: 
- inbuilt sound would be fine because not everyone (including me) has a mp3 sound library in place
- notifactions are given on every UDP update. i would have exected notif only given once (on status change), like the server status change notification is also given only once. but its good this way
