### ISSUE TITLE
relaunch does not maximize

### ISSUE THREAD

**Issue by Alvo** [Poweruser/OFPMonitor#5]
When you launch OFPMonitor (OM) while an already launched instance is sent to the system tray, the newly launched OM exits without letting the present OM maximize.

**Comment by Poweruser** [comment]
Can't reproduce this.
You shouldn't be able to launch a second instance at all. It quits right when another instance has been found (happends in OFPMonitor.cpp line 24)
And I don't see what impact a process, which basicly does nothing, could have on already running ones.

**Comment by Alvo** [comment]
Look how the Mozilla Thunderbird handles this. You start Thunderbird, and minimize to task bar. You start Thunderbird a second time, and this causes the running instance to be maximized (/reopened), while the newly launched instance exits.

**Comment by Poweruser** [comment]
added in v1.29
