### ISSUE TITLE
new version notification

### ISSUE THREAD

**Issue by spam-xx** [Poweruser/OFPMonitor#6]
Would be nice to have a new version notification and/or auto-refresh

**Comment by Poweruser** [comment]
notification: yes
updater: no

**Comment by Poweruser** [comment]
Both (notification and updater) added in v1.6.0.0

**Comment by Poweruser** [comment]
The updater is not working properly in 1.6.0.0
1) If the remote server could not be contacted for whatever reason (no connection, timeout, firewall blocking, ...), it tells "You already have the latest version".
2) the ssl libraries that the Indy Http component uses (libssl32.dll and libeay32.dll) are not included in the download. If those are missing in the users windows installation, point 1) applies.

**Comment by Poweruser** [comment]
all fixed in 1.6.0.2
