### ISSUE TITLE
IRC chatclient does not reconnect

### ISSUE THREAD

**Issue by Alvo** [Poweruser/OFPMonitor#7]
IRC chatclient does not reconnect, how to demo:
1. connect to irc
2. break TCP/IP connection e.g. by changing IP-address by router reset
3. the IRC client will not reconnect

**Comment by Poweruser** [comment]
Yep and afaik it's your chat. Get to work then.

**Comment by Poweruser** [comment]
This was added in v1.42 and changed in v1.6.0.0
OFPMonitor does reconnect to the irc chat within 1 minute, with a slightly changed username, i.e: Poweruser[2] instead of Poweruser
