### ISSUE TITLE
Server List restart difference

### ISSUE THREAD

**Issue by Alvo** [Poweruser/OFPMonitor#9]
Hi,
when i start OFPMonitor, i have servers: 
    Online 11, Listed 16
After "Get new Serverlist" with "Query the community master servers" on: 
  Online 18, Listed 18
After closing OFP-Monitor (With window close button) and starting again:
  Online: 11, Listed: 16

So e.g. the "Poofi" servers are never visible at first startup. Whats the problem here, multiple servers?
I assume correct behavior of Ofp-Monitor is to have same server list after restart :)

Thanks alot!

**Comment by Poweruser** [comment]
- Is the config file saved, when you close it? (check the "last modification" property of the file)
  - If it is saved, are the new servers listed there?
  - If it is not, does your current user account have write access for that path/file?

**Comment by Alvo** [comment]
There was a write permission problem to any existing file in insallation folder
